---
apiVersion: v1
kind: Pod
metadata:
  name: kafka1
  labels:
    app: kfk
    category: kafka
    instance: "1"
spec:
  containers:
  - name: kafka
    imagePullPolicy: Always 
    image: mbe1224/confluent-kafka
    env:
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "PLAINTEXT://kafka1:9092"
    - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
      value: "true"
    - name: KAFKA_DEFAULT_REPLICATION_FACTOR
      value: "5"            
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "5"
    - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
      value: "5"
    - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
      value: "5"
    - name: KAFKA_NUM_PARTITIONS
      value: "5"
    readinessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 10        
      timeoutSeconds: 1
    livenessProbe:
      tcpSocket:
        port: 9092
      initialDelaySeconds: 10        
      timeoutSeconds: 1           